image: ruby

# Cache gems in between builds
cache:
  paths:
    - vendor/ruby

before_script:
  - gem install awesome_bot

awesome_bot:
  script:
    - awesome_bot --allow-redirect --white-list kb.netgear.com,support.dynabook.com README.md
