
jobs:
  include:
    - name: awesome_bot
      language: ruby
      rvm:
        - 2.2
      before_script:
        - gem install awesome_bot
      script:
        - awesome_bot --allow-redirect --white-list kb.netgear.com,support.dynabook.com README.md
    - name: awesome-lint
      language: node_js
      node_js:
        - 'node'
  allow_failures:
    - name: awesome-lint